/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('CATEGORIES').del();
    await knex('CATEGORIES').insert([
        { id: 1, name: 'Салат из курицы', idSection: 1 },
        { id: 2, name: 'Классические салаты', idSection: 1 },
        { id: 3, name: 'Крабовый салат', idSection: 1 },
        { id: 4, name: 'Салат с ананасами', idSection: 1 },
        { id: 5, name: 'Селедка под шубой', idSection: 1 },
        { id: 6, name: 'Простые, легкие, быстрые салаты', idSection: 1 },
        { id: 7, name: 'Салат с сыром', idSection: 1 },
        { id: 8, name: 'Салат Оливье', idSection: 1 },
        { id: 9, name: 'Салат из кальмаров', idSection: 1 },
        { id: 10, name: 'Салат из огурцов', idSection: 1 },
        { id: 11, name: 'Салат с ананасами и курицей', idSection: 1 },
        { id: 12, name: 'Салаты из крабовых палочек', idSection: 1 },
        { id: 13, name: 'Салаты с креветками', idSection: 1 },
        { id: 14, name: 'Салат Цезарь', idSection: 1 },
        { id: 15, name: 'Салат с яйцами', idSection: 1 },
        { id: 16, name: 'Салат из кукурузы', idSection: 1 },
        { id: 17, name: 'Салаты с грибами', idSection: 1 },
        { id: 18, name: 'Салаты из моркови', idSection: 1 },
        { id: 19, name: 'Салат с капустой', idSection: 1 },
        { id: 20, name: 'Салат Мимоза', idSection: 1 },
        { id: 21, name: 'Оливье классический салат', idSection: 1 },
        { id: 22, name: 'Салат из копченой курицы', idSection: 1 },
        { id: 23, name: 'Салат с фасолью', idSection: 1 },
        { id: 24, name: 'Праздничные салаты', idSection: 1 },
        { id: 25, name: 'Корейские салаты', idSection: 1 },
        { id: 26, name: 'Винегрет', idSection: 1 },
        { id: 27, name: 'Греческий салат', idSection: 1 },
        { id: 28, name: 'Салаты с шампиньонами', idSection: 1 },
        { id: 29, name: 'Салат из помидоров', idSection: 1 },
        { id: 30, name: 'Салат из курицы с сыром', idSection: 1 },
        { id: 31, name: 'Салаты с колбасой', idSection: 1 },
        { id: 32, name: 'Салат из пекинской капусты', idSection: 1 },
        { id: 33, name: 'Салаты с печенью', idSection: 1 },
        { id: 34, name: 'Салаты с курицей и грибами', idSection: 1 },
        { id: 35, name: 'Салат с куриной грудкой', idSection: 1 },
        { id: 36, name: 'Салат с говядиной', idSection: 1 },
        { id: 37, name: 'Салаты с орехами', idSection: 1 },
        { id: 38, name: 'Салат Цезарь с курицей', idSection: 1 },
        { id: 39, name: 'Салат с сухариками', idSection: 1 },
        { id: 40, name: 'Салаты из рыбы', idSection: 1 },
        { id: 41, name: 'Салат с корейской морковью', idSection: 1 },
        { id: 42, name: 'Салаты из свеклы', idSection: 1 },
        { id: 43, name: 'Медовый торт', idSection: 2 },
        { id: 44, name: 'Торт для девочки', idSection: 2 },
        { id: 45, name: 'Классические торты', idSection: 2 },
        { id: 46, name: 'Борщ', idSection: 3 },
        { id: 47, name: 'Бульоны', idSection: 3 },
        { id: 48, name: 'Солянка', idSection: 3 },
        { id: 49, name: 'Щи', idSection: 3 },
        { id: 50, name: 'Рассольник', idSection: 3 },
        { id: 51, name: 'Пироги', idSection: 4 },
        { id: 52, name: 'Печенье домашнее', idSection: 4 },
        { id: 53, name: 'Блины и блинчики', idSection: 4 },
        { id: 54, name: 'Пирожки', idSection: 4 },
        { id: 55, name: 'Сырники', idSection: 4 },
        { id: 56, name: 'Оладьи', idSection: 4 },
        { id: 57, name: 'Шарлотка', idSection: 4 },
        { id: 58, name: 'Булочки', idSection: 4 },
        { id: 59, name: 'Ватрушки', idSection: 4 },
        { id: 60, name: 'Пироги в духовке', idSection: 4 },
        { id: 61, name: 'Шарлотка с яблоками', idSection: 4 },
        { id: 62, name: 'Блины  и блинчики на молоке', idSection: 4 },
        { id: 63, name: 'Хачапури', idSection: 4 },
        { id: 64, name: 'Лепешки', idSection: 4 },
        { id: 65, name: 'Манник - манный пирог', idSection: 4 },
        { id: 66, name: 'Пончики', idSection: 4 },
        { id: 67, name: 'Оладьи на кефире', idSection: 4 },
        { id: 68, name: 'Чизкейк', idSection: 4 },
        { id: 69, name: 'Драники', idSection: 4 },
        { id: 70, name: 'Кексы, маффины, капкейки', idSection: 4 },
        { id: 71, name: 'В духовке', idSection: 5 },
        { id: 72, name: 'На сковороде', idSection: 5 },
        { id: 73, name: 'Замораживание', idSection: 5 },
        { id: 74, name: 'Картошка в духовке', idSection: 5 },
        { id: 75, name: 'Курица в духовке', idSection: 5 },
        { id: 76, name: 'Мясо в духовке', idSection: 5 },
        { id: 77, name: 'Свинина в духовке', idSection: 5 },
        { id: 78, name: 'Фаршированные блюда', idSection: 5 },
        { id: 79, name: 'Утка в духовке', idSection: 5 },
        { id: 80, name: 'В мультиварке', idSection: 5 },
        { id: 81, name: 'Грибы в духовке', idSection: 5 },
        { id: 82, name: 'Тыква в духовке', idSection: 5 },
        { id: 83, name: 'Каша', idSection: 6 },
        { id: 84, name: 'Котлеты', idSection: 6 },
        { id: 85, name: 'Запеканки', idSection: 6 },
        { id: 86, name: 'Плов', idSection: 6 },
        { id: 87, name: 'Шашлыки', idSection: 6 },
        { id: 88, name: 'Вареники', idSection: 6 },
        { id: 89, name: 'Стейки', idSection: 6 },
        { id: 90, name: 'Чебуреки с мясом и без', idSection: 6 },
        { id: 91, name: 'Запеканка творожная', idSection: 6 },
        { id: 92, name: 'Голубцы', idSection: 6 },
        { id: 93, name: 'Каши на молоке', idSection: 6 },
        { id: 94, name: 'Пицца', idSection: 6 },
        { id: 95, name: 'Омлет', idSection: 6 },
        { id: 96, name: 'Тефтели', idSection: 6 },
        { id: 97, name: 'Гуляш', idSection: 6 },
        { id: 98, name: 'Хинкали', idSection: 6 },
        { id: 99, name: 'Отбивные', idSection: 6 },
        { id: 100, name: 'Лазанья', idSection: 6 },
        { id: 101, name: 'Крем для торта ', idSection: 6 },
        { id: 102, name: 'Рулеты и рулетики', idSection: 7 },
        { id: 103, name: 'Тарталетки', idSection: 7 },
        { id: 104, name: 'Шаурма', idSection: 7 },
        { id: 105, name: 'Заливное, холодец, студень', idSection: 7 },
        { id: 106, name: 'Канапе', idSection: 7 },
        { id: 107, name: 'Жульен', idSection: 7 },
        { id: 108, name: 'Рулет из лаваша', idSection: 7 },
        { id: 109, name: 'Дрожжевое тесто', idSection: 8 },
        { id: 110, name: 'Тесто для пиццы', idSection: 8 },
        { id: 111, name: 'Тесто для пирожков', idSection: 8 },
        { id: 112, name: 'Тесто для пирогов', idSection: 8 },
        { id: 113, name: 'Тесто для пельменей ', idSection: 8 },
        { id: 114, name: 'Квас домашний', idSection: 10 },
        { id: 115, name: 'Глинтвейн', idSection: 10 },
        { id: 116, name: 'Пюре', idSection: 11 },
        { id: 117, name: 'Курица с ананасами', idSection: 12 },
        { id: 118, name: 'Курица с грибами', idSection: 13 },
        { id: 119, name: 'Грибы с сыром', idSection: 13 },
        { id: 120, name: 'Пирожное', idSection: 14 },
        { id: 121, name: 'Курица с сыром', idSection: 15 },
        { id: 122, name: 'Мясо по-французски в духовке', idSection: 16 },
        { id: 123, name: 'Подливки', idSection: 17 },
        { id: 124, name: 'Сливочный соус', idSection: 17 },
        { id: 125, name: 'Майонез домашний', idSection: 17 },
        { id: 126, name: 'Новогодний стол', idSection: 18 },
        { id: 127, name: 'Новогодние салаты', idSection: 18 },
        { id: 128, name: 'Картошка с мясом', idSection: 19 },
        { id: 129, name: 'Помидоры с сыром', idSection: 19 },
        { id: 130, name: 'Курица с картошкой', idSection: 19 },
    ]);
};
